excluded: # case-sensitive paths to ignore during linting. Takes precedence over `included`
  - PostHogExample
  - PostHogTests
  - PostHog/Recording
  - PostHog/Utils/MethodSwizzler.swift
  - PostHog/Utils/ReadWriteLock.swift
  - PostHog/Utils/Reachability.swift
  - PostHog/Utils/NSData+PHGGZIP.h
  - PostHog/Utils/NSData+PHGGZIP.m
  - .build

disabled_rules:
  - force_cast
  - todo
  - trailing_comma
  - opening_brace

line_length: 160
file_length:
  warning: 600
  error: 1200

function_body_length:
  - 300 # warning
  - 400 # error

type_body_length:
  - 500 # warning
  - 600 # error
