excluded: # case-sensitive paths to ignore during linting. Takes precedence over `included`
  - PostHogExample
  - PostHogTests
  - PostHog/Recording
  - PostHog/Utils/MethodSwizzler.swift
  - PostHog/Utils/ReadWriteLock.swift
  - PostHog/Utils/Reachability.swift
  - PostHog/Utils/NSData+PHGGZIP.h
  - PostHog/Utils/NSData+PHGGZIP.m
  - .build
  - Pods

disabled_rules:
  - force_cast
  - todo
  - trailing_comma
  - opening_brace

line_length: 160
file_length:
  warning: 1000
  error: 1200

function_body_length:
  - 1000 # warning
  - 1200 # error

type_body_length:
  - 1000 # warning
  - 1200 # error
