excluded: # case-sensitive paths to ignore during linting. Takes precedence over `included`
  - PostHogExample
  - PostHogExampleWithSPM
  - PostHogExampleAutocapture
  - PostHogTests
  - PostHog/Utils/Reachability.swift
  - PostHog/Utils/Data+Gzip.swift
  - .build
  - Pods

disabled_rules:
  - force_cast
  - todo
  - trailing_comma
  - opening_brace

line_length:
  warning: 160
  ignores_comments: true
  excluded_lines_patterns: [
    # long deprecation messages
    \@available(.*/*deprecated.*) 
  ]

file_length:
  warning: 1000
  error: 1200

identifier_name:
  excluded:
    - id
    - ^ph_.*$

function_body_length:
  - 1000 # warning
  - 1200 # error

type_body_length:
  - 1000 # warning
  - 1200 # error
