//
//  PostHogEvent.swift
//  PostHog
//
//  Created by Manoel Aranda Neto on 13.10.23.
//

import Foundation

/// Event object passed through `BeforeSendBlock` before it is queued.
///
/// Mutate fields in your before-send callback to redact or enrich the event, or return `nil`
/// from the callback to drop it. Instances are created by the SDK; application code normally
/// captures events through `PostHogSDK.capture` instead of constructing this type.
@objc(PostHogEvent) public class PostHogEvent: NSObject {
    /// Event name, such as `"user_signed_up"` or `"$screen"`.
    @objc public var event: String

    /// Distinct ID associated with the event.
    @objc public var distinctId: String

    /// Event properties that will be serialized with the event.
    @objc public var properties: [String: Any]

    /// Event timestamp. The absolute instant is serialized in UTC, regardless of the calendar or
    /// time zone used to create it.
    @objc public var timestamp: Date

    /// Unique event identifier generated by the SDK.
    @objc public private(set) var uuid: UUID
    // Only used for Replay.
    // Publicly this remains named apiKey for BeforeSendBlock compatibility,
    // but it carries the PostHog project token and is serialized as api_key on the wire.
    var apiKey: String?

    init(event: String, distinctId: String, properties: [String: Any]? = nil, timestamp: Date = Date(), uuid: UUID = UUID.v7(), apiKey: String? = nil) {
        self.event = event
        self.distinctId = distinctId
        self.properties = properties ?? [:]
        self.timestamp = timestamp
        self.uuid = uuid
        self.apiKey = apiKey
    }

    // NOTE: Ideally we would use the NSCoding behaviour but it gets needlessly complex
    // given we only need this for sending to the API
    static func fromJSON(_ data: Data) -> PostHogEvent? {
        guard let json = fromJSONData(data) else {
            return nil
        }

        return fromJSON(json)
    }

    static func fromJSON(_ json: [String: Any]) -> PostHogEvent? {
        guard let event = json["event"] as? String else { return nil }

        let timestamp = json["timestamp"] as? String ?? toISO8601String(Date())

        let timestampDate = toISO8601Date(timestamp) ?? Date()

        var properties = (json["properties"] as? [String: Any]) ?? [:]

        // back compatibility with v2
        let setProps = json["$set"] as? [String: Any]
        if setProps != nil {
            properties["$set"] = setProps
        }

        guard let distinctId = (json["distinct_id"] as? String) ?? (properties["distinct_id"] as? String) else { return nil }

        // `message_id` is deprecated and only accepted for backwards compatibility with legacy persisted events.
        let uuid = ((json["uuid"] as? String) ?? (json["message_id"] as? String)) ?? UUID.v7String()
        let uuidObj = UUID(uuidString: uuid) ?? UUID.v7()

        // Wire field name remains api_key, but it carries the PostHog project token.
        let projectKey = json["api_key"] as? String

        return PostHogEvent(
            event: event,
            distinctId: distinctId,
            properties: properties,
            timestamp: timestampDate,
            uuid: uuidObj,
            apiKey: projectKey
        )
    }

    func toJSON() -> [String: Any] {
        var json: [String: Any] = [
            "event": event,
            "distinct_id": distinctId,
            "properties": Self.serializedProperties(properties, event: event),
            "timestamp": toISO8601String(timestamp),
            "uuid": uuid.postHogUuidString,
        ]

        if let projectToken = apiKey {
            // Wire field name remains api_key, but it carries the PostHog project token.
            json["api_key"] = projectToken
        }

        return json
    }

    /// Event-only cleanup shared by wire, queue encoding and legacy event rewrites.
    /// Typed SDK payloads retain their own null semantics; custom `$set`/`$group_set`
    /// dictionaries are not exempt. Generic storage and JSON sanitization are unchanged.
    static func serializedProperties(_ properties: [String: Any], event: String) -> [String: Any] {
        let reserved: Set<String>
        switch event {
        case "$snapshot":
            reserved = ["$snapshot_data"]
        case "$exception":
            reserved = ["$exception_list", "$debug_images"]
        case "$feature_flag_called":
            reserved = ["$feature_flag_response", "$feature_flag_reason", "$feature_flag_id", "$feature_flag_version"]
        default:
            reserved = []
        }
        return properties.reduce(into: [:]) { result, entry in
            if reserved.contains(entry.key) {
                result[entry.key] = entry.value
            } else {
                result[entry.key] = removingNullObjectMembers(entry.value)
            }
        }
    }
}

private func removingNullObjectMembers(_ value: Any) -> Any? {
    // Foundation bridges boxed Optional.none to NSNull, as JSONSerialization does.
    if value as AnyObject is NSNull {
        return nil
    }
    if let dictionary = value as? [String: Any] {
        return dictionary.reduce(into: [String: Any]()) { result, entry in
            result[entry.key] = removingNullObjectMembers(entry.value)
        }
    }
    if let array = value as? [Any] {
        // Do not compact null slots or dictionaries emptied by recursive cleanup.
        return array.map { removingNullObjectMembers($0) ?? NSNull() }
    }
    return value
}

enum PostHogKnownUnsafeEditableEvent: String {
    case snapshot = "$snapshot"
    case screen = "$screen"
    case set = "$set"
    case surveyDismissed = "survey dismissed"
    case surveySent = "survey sent"
    case surveyShown = "survey shown"
    case identify = "$identify"
    case groupidentify = "$groupidentify"
    case createAlias = "$create_alias"
    case featureFlagCalled = "$feature_flag_called"

    static func contains(_ name: String) -> Bool {
        PostHogKnownUnsafeEditableEvent(rawValue: name) != nil
    }
}
