//
//  PostHogEvent.swift
//  PostHog
//
//  Created by Manoel Aranda Neto on 13.10.23.
//

import Foundation

/// Event object passed through `BeforeSendBlock` before it is queued.
///
/// Mutate fields in your before-send callback to redact or enrich the event, or return `nil`
/// from the callback to drop it. Instances are created by the SDK; application code normally
/// captures events through `PostHogSDK.capture` instead of constructing this type.
@objc(PostHogEvent) public class PostHogEvent: NSObject {
    /// Event name, such as `"user_signed_up"` or `"$screen"`.
    @objc public var event: String

    /// Distinct ID associated with the event.
    @objc public var distinctId: String

    /// Event properties that will be serialized with the event.
    @objc public var properties: [String: Any]

    /// Options that tell PostHog how to process this event, separate from its properties.
    ///
    /// Holds the options passed to `capture(..., options:)`. Known keys are `process_person_profile`,
    /// `cookieless_mode`, `disable_skew_correction` and `product_tour_id`; unknown keys are sent
    /// unchanged and ignored by PostHog. When the event is sent, the legacy `$process_person_profile`, `$cookieless_mode`,
    /// `$ignore_sent_at` and `$product_tour_id` properties are removed from `properties` and used
    /// for their options, unless that option is set here.
    @objc public var options: [String: Any]

    /// Event timestamp. The absolute instant is serialized in UTC, regardless of the calendar or
    /// time zone used to create it.
    @objc public var timestamp: Date

    /// Unique event identifier generated by the SDK.
    @objc public private(set) var uuid: UUID
    // Only used for Replay.
    // Serialized as api_key on the wire.
    var projectToken: String?

    /// Set by the SDK when this event took the throttled replay debug bundle, so it survives `beforeSend` renames or replacement.
    var carriesReplayDebugBundle = false

    init(
        event: String,
        distinctId: String,
        properties: [String: Any]? = nil,
        options: [String: Any]? = nil,
        timestamp: Date = Date(),
        uuid: UUID = UUID.v7(),
        projectToken: String? = nil
    ) {
        self.event = event
        self.distinctId = distinctId
        self.properties = properties ?? [:]
        self.options = options ?? [:]
        self.timestamp = timestamp
        self.uuid = uuid
        self.projectToken = projectToken
    }

    // NOTE: Ideally we would use the NSCoding behaviour but it gets needlessly complex
    // given we only need this for sending to the API
    static func fromJSON(_ data: Data) -> PostHogEvent? {
        guard let json = fromJSONData(data) else {
            return nil
        }

        return fromJSON(json)
    }

    static func fromJSON(_ json: [String: Any]) -> PostHogEvent? {
        guard let event = json["event"] as? String else { return nil }

        let timestamp = json["timestamp"] as? String ?? toISO8601String(Date())

        let timestampDate = toISO8601Date(timestamp) ?? Date()

        let properties = (json["properties"] as? [String: Any]) ?? [:]

        guard let distinctId = (json["distinct_id"] as? String) ?? (properties["distinct_id"] as? String) else { return nil }

        let uuid = (json["uuid"] as? String) ?? UUID.v7String()
        let uuidObj = UUID(uuidString: uuid) ?? UUID.v7()

        // Wire field name remains api_key, but it carries the PostHog project token.
        let projectToken = json["api_key"] as? String

        return PostHogEvent(
            event: event,
            distinctId: distinctId,
            properties: properties,
            // Events queued by older versions have no options.
            options: json["options"] as? [String: Any],
            timestamp: timestampDate,
            uuid: uuidObj,
            projectToken: projectToken
        )
    }

    func toJSON() -> [String: Any] {
        var json: [String: Any] = [
            "event": event,
            "distinct_id": distinctId,
            "properties": properties,
            "timestamp": toISO8601String(timestamp),
            "uuid": uuid.postHogUuidString,
        ]

        // Stored for the queue only: each endpoint shapes its own wire format.
        if !options.isEmpty {
            json["options"] = options
        }

        if let projectToken {
            // Wire field name remains api_key, but it carries the PostHog project token.
            json["api_key"] = projectToken
        }

        return json
    }
}

enum PostHogKnownUnsafeEditableEvent: String {
    case snapshot = "$snapshot"
    case screen = "$screen"
    case set = "$set"
    case surveyDismissed = "survey dismissed"
    case surveySent = "survey sent"
    case surveyShown = "survey shown"
    case identify = "$identify"
    case groupidentify = "$groupidentify"
    case createAlias = "$create_alias"
    case featureFlagCalled = "$feature_flag_called"

    static func contains(_ name: String) -> Bool {
        PostHogKnownUnsafeEditableEvent(rawValue: name) != nil
    }
}
