#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(git rev-parse --show-toplevel)"
SNAPSHOT_FILE="$ROOT_DIR/api/posthog-ios.public-api.txt"
UPDATE=false

while [[ $# -gt 0 ]]; do
    case "$1" in
        -u|--update)
            UPDATE=true
            shift
            ;;
        -\?|-h|--help)
            cat <<'EOF'
Usage: scripts/check-public-api.sh [--update]

Checks the PostHog Swift public API snapshot.
Use --update after intentional public API changes.
EOF
            exit
            ;;
        *)
            echo "Unknown option: $1" >&2
            exit 1
            ;;
    esac
done

TMP_FILE="$(mktemp)"
DERIVED_DATA_DIR="$(mktemp -d)"
SYMBOLGRAPH_DIR="$(mktemp -d)"
cleanup() {
    rm -f "$TMP_FILE"
    rm -rf "$DERIVED_DATA_DIR" "$SYMBOLGRAPH_DIR"
}
trap cleanup EXIT

cd "$ROOT_DIR"
set -o pipefail
xcrun xcodebuild build \
    -scheme PostHog \
    -destination generic/platform=ios \
    -derivedDataPath "$DERIVED_DATA_DIR" \
    | xcpretty >/dev/null

PRODUCTS_DIR="$(find "$DERIVED_DATA_DIR/Build/Products" -maxdepth 1 -type d -name '*iphoneos' | head -n 1)"
if [[ -z "$PRODUCTS_DIR" ]]; then
    echo "No iOS build products found under $DERIVED_DATA_DIR/Build/Products" >&2
    exit 1
fi

xcrun swift-symbolgraph-extract \
    -module-name PostHog \
    -target arm64-apple-ios13.0 \
    -sdk "$(xcrun --sdk iphoneos --show-sdk-path)" \
    -I "$PRODUCTS_DIR" \
    -F "$PRODUCTS_DIR" \
    -minimum-access-level public \
    -skip-synthesized-members \
    -output-dir "$SYMBOLGRAPH_DIR"

python3 - "$SYMBOLGRAPH_DIR" "$TMP_FILE" <<'PY'
import json
import sys
from pathlib import Path

symbolgraph_dir = Path(sys.argv[1])
out = Path(sys.argv[2])
if not symbolgraph_dir.exists():
    raise SystemExit(f'No Swift symbol graph output found under {symbolgraph_dir}')

records = []
for path in sorted(symbolgraph_dir.glob('PostHog*.symbols.json')):
    data = json.loads(path.read_text())
    module = data.get('module', {}).get('name', path.stem.removesuffix('.symbols'))
    for symbol in data.get('symbols', []):
        access = symbol.get('accessLevel', '')
        if access not in {'public', 'open'}:
            continue
        kind = symbol.get('kind', {}).get('identifier', 'unknown').replace('swift.', '')
        precise = symbol.get('identifier', {}).get('precise', '')
        path_components = '.'.join(symbol.get('pathComponents', []))
        if path_components == 'char8_t' and precise.startswith('c:PostHog-Swift.h@T@'):
            continue
        declaration = ''.join(fragment.get('spelling', '') for fragment in symbol.get('declarationFragments', []))
        records.append((module, path_components, kind, declaration, precise))

if not records:
    raise SystemExit('No public PostHog symbols found in generated symbol graphs')

lines = [
    '# This file is generated by `scripts/check-public-api.sh --update`.',
    '# Do not edit manually.',
    '# Public API scope: public/open symbols emitted for the PostHog iOS symbol graphs.',
    '',
]
for module, path_components, kind, declaration, precise in sorted(set(records)):
    lines.append(f'{module} | {path_components} | {kind} | {declaration} | {precise}')

out.write_text('\n'.join(lines) + '\n')
PY

if $UPDATE; then
    mkdir -p "$(dirname "$SNAPSHOT_FILE")"
    cp "$TMP_FILE" "$SNAPSHOT_FILE"
    echo "Updated $SNAPSHOT_FILE"
    exit
fi

if [[ ! -f "$SNAPSHOT_FILE" ]]; then
    echo "Missing public API snapshot: $SNAPSHOT_FILE" >&2
    echo "Run scripts/check-public-api.sh --update to create it." >&2
    exit 1
fi

if diff -u "$SNAPSHOT_FILE" "$TMP_FILE"; then
    echo "Swift public API snapshot is up to date."
else
    echo "Swift public API changed. Run scripts/check-public-api.sh --update if intentional." >&2
    exit 1
fi
