name: Build
on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - "**/*.md"

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-15-xlarge
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: ios
            command: set -o pipefail && xcrun xcodebuild clean build -scheme PostHog -destination generic/platform=ios | xcpretty
          - platform: macos-spm
            command: set -o pipefail && xcrun swift build --arch arm64
          - platform: macos
            command: set -o pipefail && xcrun xcodebuild clean build -scheme PostHog -destination generic/platform=macos | xcpretty
          - platform: tvos
            command: set -o pipefail && xcrun xcodebuild clean build -scheme PostHog -destination generic/platform=tvos | xcpretty
          - platform: watchos
            command: set -o pipefail && xcrun xcodebuild clean build -scheme PostHog -destination generic/platform=watchos | xcpretty
          - platform: visionos
            command: set -o pipefail && xcrun xcodebuild clean build -scheme PostHog -destination generic/platform=xros | xcpretty
    name: Build SDK (${{ matrix.platform }})
    steps:
      - uses: actions/checkout@v6
      - uses: maxim-lobanov/setup-xcode@ed7a3b1fda3918c0306d1b724322adc0b8cc0a90 # v1.7.0
        with:
          xcode-version: latest-stable
      - name: Build SDK (${{ matrix.platform }})
        run: ${{ matrix.command }}
